name = "mvp-template"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Account ID - update with your Cloudflare account ID
# account_id = "your-account-id-here"

# Workers configuration
workers_dev = true

# Build configuration
[build]
command = "npm run build:worker"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-kv-id"
preview_id = "your-preview-sessions-kv-id"

# R2 Buckets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "mvp-assets"
preview_bucket_name = "mvp-assets-preview"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "mvp-uploads"
preview_bucket_name = "mvp-uploads-preview"

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "mvp-database"
database_id = "your-d1-database-id"
preview_database_id = "your-preview-d1-database-id"

# AI Gateway Configuration
[ai]
binding = "AI"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Queues
[[queues.producers]]
binding = "TASK_QUEUE"
queue = "mvp-tasks"

[[queues.consumers]]
queue = "mvp-tasks"
max_batch_size = 10
max_batch_timeout = 30

# Durable Objects
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "mvp-template"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Environment Variables (secrets should be set via wrangler secret put)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
AI_GATEWAY_ID = "your-ai-gateway-id"

# Production Environment
[env.production]
name = "mvp-template-production"
route = { pattern = "example.com/*", zone_name = "example.com" }

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"

# Staging Environment
[env.staging]
name = "mvp-template-staging"
route = { pattern = "staging.example.com/*", zone_name = "example.com" }

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"

# Observability
[observability]
enabled = true
head_sampling_rate = 1.0
