name = "mvp-template"
main = "src/worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Account ID - update with your Cloudflare account ID
# Get this from your Cloudflare dashboard
# account_id = "your-account-id-here"

# Workers configuration
workers_dev = true

# Build configuration
[build]
command = "npm run build"

###########################################
# D1 Database Configuration
###########################################
[[d1_databases]]
binding = "DB"
database_name = "mvp-database"
database_id = "your-d1-database-id"
# Create with: wrangler d1 create mvp-database
# Run migrations with: wrangler d1 execute mvp-database --file=./database/schema.sql

###########################################
# KV Namespaces Configuration
###########################################
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
# Create with: wrangler kv:namespace create "CACHE"

[[kv_namespaces]]
binding = "SESSION"
id = "your-session-kv-id"
# Create with: wrangler kv:namespace create "SESSION"

###########################################
# R2 Buckets Configuration
###########################################
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "mvp-storage"
# Create with: wrangler r2 bucket create mvp-storage

###########################################
# AI Gateway Configuration
###########################################
[ai]
binding = "AI"
# AI Gateway logs and caches your AI requests
# Configure in Cloudflare dashboard under AI > AI Gateway

###########################################
# Queue Configuration (Optional)
###########################################
# [[queues.producers]]
# binding = "TASK_QUEUE"
# queue = "task-queue"
# Create with: wrangler queues create task-queue

###########################################
# Analytics Engine (Optional)
###########################################
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

###########################################
# Environment Variables
###########################################
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"

###########################################
# Production Environment
###########################################
[env.production]
name = "mvp-template-production"
workers_dev = false
route = { pattern = "example.com/*", zone_name = "example.com" }

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"

[[env.production.d1_databases]]
binding = "DB"
database_name = "mvp-database-production"
database_id = "your-production-d1-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-production-kv-id"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "your-production-session-kv-id"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "mvp-storage-production"

###########################################
# Staging Environment
###########################################
[env.staging]
name = "mvp-template-staging"
workers_dev = false

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "mvp-database-staging"
database_id = "your-staging-d1-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-id"

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "your-staging-session-kv-id"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "mvp-storage-staging"
