name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
      reason:
        description: 'Reason for manual deployment'
        required: false
        type: string

env:
  NODE_VERSION: '20'

jobs:
  manual-deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ github.event.inputs.environment }}

      - name: Notify deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environment = '${{ github.event.inputs.environment }}';
            const reason = '${{ github.event.inputs.reason }}' || 'No reason provided';
            const message = `✅ Manual deployment to **${environment}** completed successfully!
            
            **Reason:** ${reason}
            **Deployed by:** @${{ github.actor }}
            **Commit:** ${context.sha.substring(0, 7)}`;
            
            console.log(message);
